//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Usuarios
    {
        public System.Guid id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public string telefono { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<System.Guid> UsuarioCreado { get; set; }
        public Nullable<System.Guid> UsuarioModificado { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public string IdFacebook { get; set; }
        public string IdTwitter { get; set; }
        public string IdGooglePlus { get; set; }
        public Nullable<System.Guid> FK_Rol { get; set; }
    }
}
